### ISSUE TITLE
Copy of Angular2-JWT

### ISSUE THREAD

**Issue by sallar** [HaidarZ/ng2-auth#1]
Hi, 

This module and it's readme is an almost exact copy of [`angular-jwt`](https://github.com/auth0/angular2-jwt) package. Is there a reason that you have not mentioned that in the README?

**Comment by HaidarZ** [comment]
Hi,
It's a rewrite of angular-jwt , without the jwt part , just as simple auth , you can checkout the source code if you like :).
It's my fault not mentioning the jwt 👍
